on: workflow_dispatch
jobs:
  release:
    if: github.ref_type == 'tag'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: liberica
          java-version: "21"
      - uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false
      - run: echo "${{ secrets.SIGNING_SECRING_FILE }}" | base64 -d > ${{ github.workspace }}/secring.gpg
      - run: >
          ./gradlew publishMavenPublicationToMavenCentralStagingRepository
          -Psigning.keyId=${{ secrets.SIGNING_KEY_ID }}
          -Psigning.password=${{ secrets.SIGNING_PASSWORD }}
          -Psigning.secretKeyRingFile=${{ github.workspace }}/secring.gpg
          -PmavenCentralStagingUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}
          -PmavenCentralStagingPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}
